server:
  port: 4500
---
environment: prod
myCustomVarTree:
  customInt: 2
  customInt2: 8
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 5000
---
environment: test
spring:
  config:
    activate:
      on-profile: test
server:
  port: 4000